### ISSUE TITLE
 Error installing latest version

### ISSUE THREAD

**Issue by alisson9386** [pluginsGLPI/formcreator#2028]
Hello, could you help me please? I updated my GLPI to version 9.5.2 and when installing formcreator, the error below appears:

Upgrade glpi_plugin_formcreator_questions_conditions (0 seconds)

What is the solution for this case?
Thank you very much in advance

**Comment by btry** [comment]
Hi

Did you a fresh install of the plugin or an upgrade ?

**Comment by alisson9386** [comment]
I updated the plugin

**Comment by btry** [comment]
Hi

Which was the previous version of the plugin ?

**Comment by alisson9386** [comment]
2.6.5

**Comment by btry** [comment]
Back somewhere near this versin there was a bug in the installer which will impact current versions.

Please show the result of the followingrequest 

```sql
SELECT * from glpi_configs WHERE context='formcreator';
```

Also, please cehck in glpi/files/_logs the file migration_to_2.10.4.log (I assume you tried to install the version 2.10.4).

Check also glpi/files/_logs/php-errors.log, glpi/files/_log/sql-errors.log and the logs of your HTTP server (for a HTTP 500 error)

If you find warnings or errors, please show them here.

**Comment by alisson9386** [comment]
**Those were the results of the mysql search:**

Database changed
mysql> SELECT * from glpi_configs WHERE context='formcreator';
Empty set (0.00 sec)


**First log return**

root@SRV23:~# tail -f /var/www/html/files/_log/migration_to_2.10.4.log
0 segundo for "Trabalho em progresso..." @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade to schema version 2.5" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_answers" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_categories" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_answers" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_profiles" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_forms_validators" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Upgrade glpi_plugin_formcreator_forms" @ 2020-11-25 19:24:09 [19@SRV23]
0 segundo for "Drop glpi_plugin_formcreator_headers" @ 2020-11-25 19:24:11 [19@SRV23]
2 segundos for "Upgrade glpi_plugin_formcreator_issues" @


**in the php-errors.log file there were no errors**


**Below the sql-errors.log errors**

root@SRV23:~# tail -f /var/www/html/files/_log/sql-errors.log
  plugins/dashboard/front/metrics/index.php:21       include()
  {"user":"@SRV23"}
[2020-11-26 11:01:11] glpisqllog.ERROR: DBmysql::query() in /var/www/html/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: SELECT value FROM glpi_plugin_dashboard_config WHERE name = 'entity' AND users_id =
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
  Backtrace :
  ...ins/dashboard/front/metrics/metrics.inc.php:115
  plugins/dashboard/front/metrics/index.php:21       include()
  {"user":"@SRV23","mem_usage":"0.000\", 3.25Mio)"}

**Comment by alisson9386** [comment]
Good Morning!

has some return?

**Comment by btry** [comment]
Hi

Sorry I missed to continue with this ticket.

Your problem occurs because the installer failed to determine the  version of your schema. The value which hints the installer is missing. 
Run the following query to add it

```sql
INSERT into glpi_configs SET `context`='formcreator', `name`='schema_version', `value`='2.6'
```

then try again. The log in hte begiinning should tell it tries to upgrade to 2.7 (

**Comment by alisson9386** [comment]
Hi, no problem!

Below is the error message after Insert:

Done (0 segundo)

Done (0 segundo)

Done (0 segundo)

Done (0 segundo)

Done (0 segundo)

Done (0 segundo)

Alteração de layout do banco de dados - glpi_plugin_formcreator_targettickets (0 segundo)

2.10.4 multiple alter in glpi_plugin_formcreator_targettickets - Erro na consulta ao banco de dados: ALTER TABLE `glpi_plugin_formcreator_targettickets` ADD `type_rule` INT(11) NOT NULL DEFAULT '0' AFTER `target_name` , ADD `show_rule` INT(11) NOT NULL DEFAULT '1' AFTER `location_question` - Erro é Unknown column 'location_question' in 'glpi_plugin_formcreator_targettickets'

**Comment by btry** [comment]
I guess that for some reason the location_question column was not created.

Compare the table **glpi_plugin_formcreator_targettickets**  against its CREATE TABLE statement here https://github.com/pluginsGLPI/formcreator/blob/develop/install/mysql/plugin_formcreator_empty.sql#L185

If location_rule and/or location_question are missing, add them. Ensure that you maintain the columns order as described in the CREATE TABLE statement.

Once done, try again to upgrade.

**Comment by alisson9386** [comment]
I managed with that help.

I created the missing tables with the commands below:

/ * Table: glpi_plugin_formcreator_targettickets * /

ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `type_rule` int (11) NOT NULL DEFAULT '0' AFTER` target_name`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `location_rule` INT (11) NOT NULL DEFAULT '1' AFTER` associate_question`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `location_question` int (11) NOT NULL DEFAULT '0' AFTER` location_rule`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `show_rule` int (11) NOT NULL DEFAULT '1' AFTER` location_question`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `sla_rule` int (11) NOT NULL DEFAULT '1' AFTER` show_rule`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `sla_question_tto` int (11) NOT NULL DEFAULT '0' AFTER` sla_rule`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `sla_question_ttr` int (11) NOT NULL DEFAULT '0' AFTER` sla_question_tto`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `ola_rule` int (11) NOT NULL DEFAULT '1' AFTER` sla_question_ttr`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `ola_question_tto` int (11) NOT NULL DEFAULT '0' AFTER` ola_rule`;
ALTER TABLE glpi_plugin_formcreator_targettickets ADD COLUMN `ola_question_ttr` int (11) NOT NULL DEFAULT '0' AFTER` ola_question_tto`;

/ * Table: glpi_plugin_formcreator_targetchanges * /

ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `urgency_rule` int (11) NOT NULL DEFAULT '1' AFTER` due_date_period`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `urgency_question` int (11) NOT NULL DEFAULT '0' AFTER` urgency_rule`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `category_rule` int (11) NOT NULL DEFAULT '1' AFTER` tag_specifics`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `category_question` int (11) NOT NULL DEFAULT '0' AFTER` category_rule`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `show_rule` int (11) NOT NULL DEFAULT '1' AFTER` category_question`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `sla_rule` int (11) NOT NULL DEFAULT '1' AFTER` show_rule`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `sla_question_tto` int (11) NOT NULL DEFAULT '0' AFTER` sla_rule`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `sla_question_ttr` int (11) NOT NULL DEFAULT '0' AFTER` sla_question_tto`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `ola_rule` int (11) NOT NULL DEFAULT '1' AFTER` sla_question_ttr`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `ola_question_tto` int (11) NOT NULL DEFAULT '0' AFTER` ola_rule`;
ALTER TABLE glpi_plugin_formcreator_targetchanges ADD COLUMN `ola_question_ttr` int (11) NOT NULL DEFAULT '0' AFTER` ola_question_tto`;


After that, the plugin worked correctly.

Thank you very much for the excellent help!

**Comment by btry** [comment]
Hi

If all those columns were missing, I advice you search in all other tables for a possible missing column. If a column ils still missing you will have bugs later.
