### ISSUE TITLE
Error after updating to 2.11

### ISSUE THREAD

**Issue by rajabiy** [pluginsGLPI/formcreator#2111]
**Describe the bug**
After updating plug-in i got an error in form edition and when reviving forms

**To Reproduce**
Version of plug-in 2.11
version of glpi 9.5.3  

**Screenshots**
![изображение](https://user-images.githubusercontent.com/7335946/106462068-69b20800-64b7-11eb-88b3-9c76e84c6eac.png)

`Warning: Cannot modify header information - headers already sent by (output started at /var/www/plugins/formcreator/setup.php:258) in /var/www/inc/html.class.php on line 1208

Warning: Cannot modify header information - headers already sent by (output started at /var/www/plugins/formcreator/setup.php:258) in /var/www/inc/html.class.php on line 1210

Warning: Cannot modify header information - headers already sent by (output started at /var/www/plugins/formcreator/setup.php:258) in /var/www/inc/html.class.php on line 2212

Warning: Cannot modify header information - headers already sent by (output started at /var/www/plugins/formcreator/setup.php:258) in /var/www/inc/html.class.php on line 2213`

**Comment by btry** [comment]
Hi

I did not saw this error yet. I guess you had a PHP error output (with debug mode enabled). Please read glpi/files/_log/php-errors.log and glpi/files/_log/sql-errors.log

I think you will find errors and backtraces. Please share them.

Also, as a side note, you should ave an upgrade issue, which will ve fixed in the next release. https://github.com/pluginsGLPI/formcreator/pull/2102 . Run the solution, method 2 available in the PR description.

**Comment by btry** [comment]
The above PR should fix the issue

**Comment by rajabiy** [comment]
[php-errors.log](https://github.com/pluginsGLPI/formcreator/files/5904368/php-errors.log)
That is file yo are asking

**Comment by btry** [comment]
That's strange : the error never occured on my side. But I must admit that the line responsible of the error is risky. Try the PR and let's see if the error disappears.

**Comment by rajabiy** [comment]
I have run that 2 queries firs one inserted 10 rows second 0 rows
but error still presented even if Iog out and in again.

**Comment by btry** [comment]
the 2 quesries are for an other problem. Just because I know that people don't read much closed issues.

Try to apply #2112 . The error should be fixed with this patch.

**Comment by rajabiy** [comment]
Thank you this patch worked for me

**Comment by btry** [comment]
Thank you for your feedback; I close.
