### ISSUE TITLE
Incorrect display of some tickets via form.

### ISSUE THREAD

**Issue by eleducq** [pluginsGLPI/formcreator#2568]
Currently under GLPI 10.0.0 with the version of formcreator Alpha.3. Some tickets appear this way when you open them, although the preview in the list is correct :

![image](https://user-images.githubusercontent.com/98739327/151994483-90d6f18c-b1a6-4836-8001-b9c2adee2886.png)
![image](https://user-images.githubusercontent.com/98739327/151994545-e46d8221-1f39-4eb8-98cd-c0828bdbdf1d.png)

While some other tickets are displayed correctly either in preview or when opening the ticket.
In addition, when creating a new ticket, the display error also appears.

**Comment by btry** [comment]
Duplicate #2543 #2521

**Comment by btry** [comment]
The ticket has been created 2 weeks ago. I guess Formcreator Alpha.2 was running at this time ?

**Comment by eleducq** [comment]
No, I switched to a dev version only last week, and I already observed this problem when I switched to V10 of GLPI with Alpha.2 as Alpha.3

**Comment by eleducq** [comment]
> Duplicate #2543 #2521

Have you already tested ticket #2543 on the latest version of GLPI?

**Comment by eleducq** [comment]
> Duplicate #2543 #2521

Have you already tested ticket #2543 on the latest version Alpha.3 ?

**Comment by btry** [comment]
I create tickets nearly every day, but I did not saw this problem. Very likely because i did not fill a form containing a text area question. This is probably this type of question which triggers the bug.

Now I need to allocate some time to validate this assumption.

**Comment by eleducq** [comment]
#2543 
Unfortunately does not correct the problem of displaying data in html

**Comment by btry** [comment]
Ok, I did a try with a textarea. I reproduce. When a form does not contains such question the ticket is properly generated.

The problems seems to be related to the text returned by the rich text area. symbols < and > used to mark HTML tags are escaped in the form &#60; and &#62; instead of &lt; and &gt;.

If I fix them, the ticket is correct. Remains to find where the bad conversion occurs.

**Comment by btry** [comment]
Please try the above fix and feedback.

**Comment by eleducq** [comment]
I've just tested this patch but it doesn't seem to fix the display of existing tickets as well as new tickets

**Comment by btry** [comment]
The patch shall fix the generation of new tickets, not those already existing. On my side, it seems to work as expected.

### before

![image](https://user-images.githubusercontent.com/14139801/152186146-20f4f141-1d49-4cbc-9944-04bbf1296409.png)


### after

![image](https://user-images.githubusercontent.com/14139801/152186066-b471e8cd-9c3b-4444-909f-4a992c273cca.png)


Maybe there is something else in your questions which triggers the bug. Please export your form (verify that you don't expose sensitive data), and upload it here.

You may also try a simple form with a textarea question, to check whtout and with the patch if you get the same results as above.

**Comment by eleducq** [comment]
This is one of the most enhanced forms I currently use as it has an html table as well as enhanced text boxes.

[glpi.csv](https://github.com/pluginsGLPI/formcreator/files/7992377/glpi.csv)

**Comment by btry** [comment]
Hi

I cannot use this export. You must use the export feature of Formcreator, generating a .json file.

Open the list of forms, select your form, and open massive actions. Choose "Export"

**Comment by eleducq** [comment]
Sorry my bad.
[export_formcreator_20220203_0901.zip](https://github.com/pluginsGLPI/formcreator/files/7992776/export_formcreator_20220203_0901.zip)

**Comment by btry** [comment]
Hi

The fix is updated, I got one satisfying fedback. Could you cancel the patch, re download it and try again ?

**Comment by eleducq** [comment]
No worries, I'll try this in the morning and get back to you as soon as possible, thanks again

**Comment by eleducq** [comment]
Thanks, everything looks good!

**Comment by eleducq** [comment]
I may be going too fast, but I don't understand why some of my tickets don't display correctly, even though they don't seem to be any different from others that work perfectly.

**Comment by btry** [comment]
Hi

So using the same form you have tickets properly rendered and tickets with the bug ?

**Comment by eleducq** [comment]
I am doing a complete reinstallation this afternoon, I will come back to you after that

**Comment by triplility** [comment]
@btry Hi, may I ask how to upgrade from alpha2 to alpha3?

**Comment by btry** [comment]
Hi

use the CLI tool of glpi

```bin/console glpi:plugin:install formcreator -f -p force-upgrade -u glpi```

**Comment by triplility** [comment]
> 
Copy the new version directly under the plugins folder, overwrite the old folder, and execute this command, is it right?

**Comment by btry** [comment]
> Copy the new version directly under the plugins folder, overwrite the old folder

no : move the old folder out of GLPI, then copy the new version. Never overwrite a plugin with a new version to upgrade. If a file existed and does not exists anymore this fille will remain, and generaly speaking the presence of an extrafile is unpredictable. It depends on the design of its logic of the plugin.

**Comment by triplility** [comment]
done, but it's the same as before.

**Comment by btry** [comment]
After the installation of Alpha.3 you need to apply this fix : 
https://github.com/pluginsGLPI/formcreator/pull/2571

I have a positive feedback, but I wish to have some more.

**Comment by triplility** [comment]
ok, I miss the fix, let me do it tomorrow, thanks :)

**Comment by triplility** [comment]
> After the installation of Alpha.3 you need to apply this fix : #2571
> 
> I have a positive feedback, but I wish to have some more.

But it doesn't look like it's just happening in taxtarea

**Comment by btry** [comment]
Then tell the other impacted types, please, and I'll investigate.

**Comment by eleducq** [comment]
After a clean reinstallation of GLPI 10, as well as the plugin, it seems to work well on my side.

**Comment by btry** [comment]
ok, I guess you tested some tickets, applied the patch and checkd if those tickets are fixed. The fix solved the problems for tickets created when the fix is applied. older tickets are not fixed (it is too late for them)

**Comment by eleducq** [comment]
For the old tickets, some have been corrected, others not, it depends.

**Comment by btry** [comment]
No old ticket has been corrected : the fix does nothing with them (it would be required to update rows in the DB)

**Comment by triplility** [comment]
> Then tell the other impacted types, please, and I'll investigate.

![image](https://user-images.githubusercontent.com/96858670/152949735-722dd788-6e96-48bb-8d22-f9e1a1b77e06.png)

I try to re install glpi10 from beta to RC1, and re-install formcreator to alpha 3 and update fix, but it look like still not work for me.

**Comment by btry** [comment]
Export the form to get its JSON representation, and send it here. I'll try to reproduce with it.

**Comment by triplility** [comment]
[export_formcreator_20220209_0533.zip](https://github.com/pluginsGLPI/formcreator/files/8029776/export_formcreator_20220209_0533.zip)
@btry  thanks

**Comment by husisusi** [comment]
I can confirm this issue using git version.

**Comment by btry** [comment]
Hi

I did some tests with a checkboxes question and I reproduce.

**Comment by btry** [comment]
Please test the above fix and feedback. It operates on checkboxes, multiselect and actors

**Comment by husisusi** [comment]
> Please test the above fix and feedback. It operates on checkboxes, multiselect and actors

It's much better! But still has a issue:
![grafik](https://user-images.githubusercontent.com/8606735/153903369-3cbd5b40-281c-4681-874a-78c85beb0dd9.png)

**Comment by triplility** [comment]
> html rendering in targets #2591

yes, It's much better! just as same as above. some type can see <br />

**Comment by btry** [comment]
Hi

@husisusi @triplility do you both use the release 2.13.0-alpha.3 or a more recent revision ? In my bugfix research I don't have the HTML tag br in the ticket (latest revision). I'll have a look on the tagged revision to see if I can reproduce.

**Comment by husisusi** [comment]
> Hi
> 
> @husisusi @triplility do you both use the release 2.13.0-alpha.3 or a more recent revision ? In my bugfix research I don't have the HTML tag br in the ticket (latest revision). I'll have a look on the tagged revision to see if I can reproduce.

It was git master version. With  2.13.0-alpha.3 and #2591 no issue. Thank you @btry !!

**Comment by btry** [comment]
Hi I updated the PR. Please remove the previous fix, download the re-apply it, then feedback.

**Comment by husisusi** [comment]
> Hi I updated the PR. Please remove the previous fix, download the re-apply it, then feedback.

Done, it works as expected.

**Comment by btry** [comment]
Hi

@triplility can you feedback please ?

**Comment by triplility** [comment]
> Hi
> 
> @triplility can you feedback please ?

Great! it's work fine! thanks so much!

**Comment by btry** [comment]
Hi

Thank you for your feedback; I close this issue.
