### ISSUE TITLE
GLPI 10 RC2 / Formcreator ALPHA 3 Unknown column 'glpi_plugin_formcreator_forms.plugin_formcreator_categories_id'

### ISSUE THREAD

**Issue by stdglpi** [pluginsGLPI/formcreator#2629]
**Describe the bug**

Hello, I upgraded my GLPI 10 RC1 to RC2
I also upgraded the Formcreator plugin to the latest formcreator Alpha 3

Now If I try to import my forms I have this error

![image](https://user-images.githubusercontent.com/63521311/157263743-347aebbe-ff31-4410-a014-44c565fc5c35.png)

GLPI 10.0.0-rc2 ( => C:\inetpub\wwwroot\glpi)
Installation mode: TARBALL
Current language:fr_FR

Operating system: Windows NT SRV-GLPI 10.0 build 14393 (Windows Server 2016) i586
PHP 8.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, soap, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.27
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP

news                 Name: Alertes                        Version: 1.10.0-rc2 State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: Enabled
	tag                  Name: Gestion des tags               Version: 2.9.0-rc3  State: Installed / not activated

**Comment by btry** [comment]
Hi

It looks like you upgraded Formcreator from 2.13.0-alpha.2 to 2.13.0-aplha.3.

If I'm right, then you must  tu run a forced upgrade of the plugin to fix the missing columns .

locate in the glpi directory then type the following command
```
php bin/console glpi:plugin:install -f -p force-upgrade formcreator
```

it will ask you the name of a user. Use a super admin account (usually glpi)

**Comment by stdglpi** [comment]
Hello @btry 

After this command, I used "GLPI" user and I have theses messages : 
![image](https://user-images.githubusercontent.com/63521311/157402639-bec6bcde-b9c5-4991-8d80-eccbe0c1f021.png)

**Comment by btry** [comment]
Hi

Those warinings are normal. GLPI 10 changed the type of ID in all its tables and the tables of the tables of Formcreator are not using this  change yet in your instance.

You need to run ```bin/console glpi:migration:unsigned_keys``` to fix that.

**Comment by stdglpi** [comment]
@btry 

Ok, I passed the command line and the result is "OK"

`php bin/console glpi:migration:unsigned_keys`

![image](https://user-images.githubusercontent.com/63521311/157644000-859a1b01-335e-4d31-b714-ddfd68fbc330.png)

After that, if I pass the command 
`php bin/console glpi:plugin:install -f -p force-upgrade formcreator`

it still shows the same errors 
![image](https://user-images.githubusercontent.com/63521311/157644352-cdc2d75d-9a1d-4f8e-9544-8e258ad2abea.png)

I missed something ?

**Comment by btry** [comment]
It looks like the migration procedure does not detects some columns as requiring a change. 

This is probably fixed with the latest revision of the branch support/2.13.0. Do you have skills to build it (needs composer, yarn, and PHP dev dependencies )

**Comment by stdglpi** [comment]
> It looks like the migration procedure does not detects some columns as requiring a change.
> 
> This is probably fixed with the latest revision of the branch support/2.13.0. Do you have skills to build it (needs composer, yarn, and PHP dev dependencies )?

Hello @btry no at all :'(.
I can't wait is not urgent.

Can I downgrade to the previous Alpha ? it will works ?

Otherwise, I disable the plugin Formcreator for the moment.

I keep an eye on the next revision.

thank you

**Comment by btry** [comment]
You can downgrade to the Alpha.3 but this is not a good idea as many changes were done and they will be included in the next Alpha, beta or final release. 

I'm interested to check the structure of all the tabls of the plugin in your instance, to see if there are still ID migration issues. Can you share here the CREATE TABLE statements od the tables, issued by SHOW CREATE TABLE query ?

**Comment by btry** [comment]
Here is a build of the latest revision of support/2.13.0


[formcreator_2.13.0-alpha.3-dev.zip](https://github.com/pluginsGLPI/formcreator/files/8231290/formcreator_2.13.0-alpha.3-dev.zip)

**Comment by stdglpi** [comment]
Replaced with formcreator_2.13.0-alpha.3-dev.zip, passed the command : 
 php bin/console glpi:plugin:install -f -p force-upgrade formcreator

still the same 
![image](https://user-images.githubusercontent.com/63521311/159464847-8a799dc9-b43f-487f-ba6b-50b8a404f376.png)

**Comment by btry** [comment]
Hi

Add the missing column manually with your favourite tool :

```sql
ALTER TABLE glpi_plugin_formcreator_forms add column plugin_formcreator_categories_id int unsigned not null DEFAULT  '0' AFTER `content`;

ALTER TABLE glpi_plugin_formcreator_forms add INDEX `plugin_formcreator_categories_id` (`plugin_formcreator_categories_id`)
```

then check you have a table glpi_plugin_formcreator_categories. If not create it with the following SQL

```sql
CREATE TABLE `glpi_plugin_formcreator_categories` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`comment` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`completename` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`plugin_formcreator_categories_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`level` INT(10) NOT NULL DEFAULT '1',
	`sons_cache` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`ancestors_cache` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`knowbaseitemcategories_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `name` (`name`) USING BTREE,
	INDEX `knowbaseitemcategories_id` (`knowbaseitemcategories_id`) USING BTREE,
	INDEX `plugin_formcreator_categories_id` (`plugin_formcreator_categories_id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
```

**Comment by btry** [comment]
> I noticed a weird thing, if i'm checking the form on the assistance menu.

it seems they have not display, I have to click on the "house logo".
Before by default they appears directly.

This behavior is wanted, but last week, I referted it. The revert is waiting for review and should be available in the Alpha.4 version, planned this week.

**Comment by stdglpi** [comment]
@btry  perfect :) 

You can close this ticket.

have a good day
